#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $CUSTOMER_PAYMENT_DB_USER WITH PASSWORD '$CUSTOMER_PAYMENT_DB_PASSWORD';
    CREATE DATABASE $CUSTOMER_PAYMENT_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $CUSTOMER_PAYMENT_DB_NAME TO $CUSTOMER_PAYMENT_DB_USER;
    ALTER DATABASE $CUSTOMER_PAYMENT_DB_NAME SET TIMEZONE='Europe/Amsterdam';
EOSQL
