#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SHIPPING_DB_USER WITH PASSWORD '$SHIPPING_DB_PASSWORD';
    CREATE DATABASE $SHIPPING_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $SHIPPING_DB_NAME TO $SHIPPING_DB_USER;
    ALTER DATABASE $SHIPPING_DB_NAME SET TIMEZONE='Europe/Amsterdam';
EOSQL