spring:

  r2dbc:
    username: ${app.postgres.user}
    password: ${app.postgres.password}
    url: r2dbc:postgresql://${app.postgres.host}:${app.postgres.port}/${app.postgres.database}
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://${app.postgres.host}:${app.postgres.port}/${app.postgres.database}

  keycloak:
    server-url: http://localhost:8080
    server-external-url: http://localhost:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.keycloak.server-external-url}/realms/stock-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/stock-realm/protocol/openid-connect/certs

  cloud:
    function:
      definition: orderOrchestrator
    stream:
      default:
        producer:
          useNativeEncoding: true
          partition-count: 2
        consumer:
          concurrency: 2
      bindings:
        orderOrchestrator-in-0:
          destination: payment-response,inventory-response,shipping-response
          group: order-service-group
        payment-request-channel:
          destination: payment-request
        inventory-request-channel:
          destination: inventory-request
        shipping-request-channel:
          destination: shipping-request
      kafka:
        binder:
          autoCreateTopics: true
          replicationFactor: 2
          brokers: ${app.kafka.brokers}
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "net.greeta.stock.common.messages.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer

app:
  postgres:
    host: stock-postgres
    port: 5432
    database: orderdb
    user: orderdbuser
    password: dbpass

  kafka:
    brokers: "stock-kafka1:29092,stock-kafka2:29093"

openapi:
  oauthflow:
    authServerUrl: ${spring.keycloak.server-external-url}
    realm: stock-realm

jwt:
  auth:
    converter:
      resource-id: stock-app
      principal-attribute: preferred_username